name: user_repository
description: dart package which manages the user
publish_to: "none"

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.2
  equatable: ^2.0.5
  firebase_auth: ^4.14.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
