name: student_repository
description: dart package which manages the students
publish_to: "none"

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
