// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzJgXs2mdisqAxOxWU8Q_32WqqIVOl_H8',
    appId: '1:653882674009:web:911282bd37d635c546da48',
    messagingSenderId: '653882674009',
    projectId: 'lockers-app-40f8d',
    authDomain: 'lockers-app-40f8d.firebaseapp.com',
    databaseURL: 'https://lockers-app-40f8d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockers-app-40f8d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJsZnxuPejOLFZaYF8fOEA79VP0fzES4o',
    appId: '1:653882674009:android:7cb33fc3e06246c746da48',
    messagingSenderId: '653882674009',
    projectId: 'lockers-app-40f8d',
    databaseURL: 'https://lockers-app-40f8d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockers-app-40f8d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGUcG0gJTjLqBFAe6D0sta1zXP4Q-WDM',
    appId: '1:653882674009:ios:e86a109c7e55c55046da48',
    messagingSenderId: '653882674009',
    projectId: 'lockers-app-40f8d',
    databaseURL: 'https://lockers-app-40f8d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockers-app-40f8d.appspot.com',
    iosBundleId: 'com.example.lockersAppBlocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoGUcG0gJTjLqBFAe6D0sta1zXP4Q-WDM',
    appId: '1:653882674009:ios:135bdf6656ca82d746da48',
    messagingSenderId: '653882674009',
    projectId: 'lockers-app-40f8d',
    databaseURL: 'https://lockers-app-40f8d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'lockers-app-40f8d.appspot.com',
    iosBundleId: 'com.example.lockersAppBlocs.RunnerTests',
  );
}
